/**
 * Xuất file Excel test case cho TASK 3575 — [App|Web][Football][Lineup -
 * Player Pop up] So sánh cầu thủ trước trận.
 *
 * Breadcrumb: Pre-Match → Details → Lineups → Select any player → Show
 * pop-up player details → Select icon compare.
 *
 * KHÔNG phải test verify — chỉ generate tài liệu Excel từ danh sách case đã
 * soạn theo User Story (US-01 Player vs Player, US-02 Player vs Team) +
 * Onboarding + Business Rules chung. Feature CHƯA lên staging tại thời điểm
 * viết case này — dùng để QA test tay khi feature deploy.
 *
 * CHẠY:
 *   npx playwright test tests/standard/2026-Q3-task-3575-compare-player-lineup/00-export-test-cases.spec.ts --project=chrome
 */

import { test } from '@playwright/test';
import { saveExcelForSeason, type ExcelSheetSpec } from '../lib/helpers';

const SEASON_DIR = '2026-Q3';
const SLUG = 'task-3575-compare-player-lineup';

type TestCaseRow = {
  id: string;
  category: string;
  title: string;
  precondition: string;
  steps: string;
  expected: string;
  priority: 'High' | 'Medium' | 'Low';
};

const TEST_CASES: TestCaseRow[] = [
  // ---- A. Breadcrumb & entry point ----
  {
    id: 'CMP-01',
    category: 'A. Entry point',
    title: 'Truy cập tính năng So sánh đúng breadcrumb từ Lineups pre-match',
    precondition: 'Đang xem trận đấu ở trạng thái Pre-Match, tab Details → Lineups đã hiển thị',
    steps: '1. Chọn bất kỳ cầu thủ nào trong Lineups\n2. Popup player details hiện ra\n3. Chọn icon "compare"',
    expected: 'Mở đúng màn hình So sánh cầu thủ, cầu thủ vừa chọn được tự động gán là Cầu thủ 1 (theo đúng breadcrumb: Pre-Match → Details → Lineups → Select player → Popup → Select icon compare)',
    priority: 'High',
  },
  {
    id: 'CMP-02',
    category: 'A. Entry point',
    title: 'Icon compare hiển thị ở cả App và Web',
    precondition: 'Đã có design App + Web',
    steps: '1. Mở popup player details trên Web\n2. Mở popup player details trên App',
    expected: 'Cả 2 nền tảng đều có icon compare, đúng theo design đã link (UI Pop-up so sánh App/Web)',
    priority: 'Medium',
  },

  // ---- B. Onboarding (hướng dẫn lần đầu sử dụng) ----
  {
    id: 'CMP-03',
    category: 'B. Onboarding',
    title: 'Onboarding hiển thị đủ 4 bước theo đúng thứ tự và nội dung',
    precondition: 'Lần đầu tiên user mở tính năng So sánh (chưa từng thấy onboarding)',
    steps: '1. Mở tính năng so sánh lần đầu\n2. Quan sát tuần tự 4 bước hướng dẫn',
    expected:
      '1/4 chỉ vào icon so sánh: "So sánh các cầu thủ trong trận"\n2/4 chỉ vào component đối tượng so sánh: "Chọn đối tượng so sánh theo danh sách bên dưới"\n3/4 chỉ vào cầu thủ: "So sánh thông số với đối thủ"\n4/4 chỉ vào đội bóng: "So sánh thông số với đội bóng"\nĐúng thứ tự, đúng nội dung, đúng vị trí trỏ (target UI)',
    priority: 'High',
  },
  {
    id: 'CMP-04',
    category: 'B. Onboarding — BR1',
    title: 'BR1: Onboarding chỉ hiển thị 1 lần duy nhất cho mỗi step',
    precondition: 'Đã xem qua đủ 4 bước onboarding ở lần mở đầu tiên',
    steps: '1. Đóng tính năng so sánh\n2. Mở lại tính năng so sánh (cùng tài khoản/thiết bị)',
    expected: 'Onboarding KHÔNG hiển thị lại — đã xem đủ 4 bước thì không lặp lại lần sau',
    priority: 'High',
  },
  {
    id: 'CMP-05',
    category: 'B. Onboarding — BR1',
    title: 'Người dùng thoát onboarding giữa chừng (ví dụ mới xem 2/4 bước)',
    precondition: 'Đang ở bước 2/4 của onboarding',
    steps: '1. Thoát tính năng so sánh giữa chừng (không xem hết 4 bước)\n2. Mở lại tính năng so sánh',
    expected: '[CẦN CONFIRM] Onboarding có tiếp tục từ bước đã dừng, phát lại từ đầu, hay coi như đã xem và không hiện nữa? Spec chỉ nói "hiển thị 1 lần duy nhất cho mỗi step" — cần làm rõ hành vi khi thoát dở dang',
    priority: 'Medium',
  },
  {
    id: 'CMP-06',
    category: 'B. Onboarding — BR2',
    title: 'BR2: Onboarding hiển thị đúng theo ngôn ngữ hệ thống đang chọn',
    precondition: 'Hệ thống hỗ trợ nhiều ngôn ngữ (vd EN, VI, ...)',
    steps: '1. Đổi ngôn ngữ hệ thống sang tiếng Anh, mở tính năng so sánh lần đầu (tài khoản/thiết bị mới)\n2. Đổi ngôn ngữ sang tiếng Việt, lặp lại',
    expected: 'Nội dung 4 bước onboarding được dịch đúng theo từng ngôn ngữ tương ứng, không bị sót ngôn ngữ nào hoặc hiển thị fallback sai',
    priority: 'Medium',
  },

  // ==== US-01: Player vs Player ====

  // ---- C. Chọn cầu thủ ----
  {
    id: 'CMP-07',
    category: 'C. US-01 — Chọn cầu thủ',
    title: 'Cầu thủ chọn từ Lineups tự động là Cầu thủ 1',
    precondition: 'Đã vào màn hình so sánh từ 1 cầu thủ cụ thể trong Lineups',
    steps: '1. Quan sát vị trí "Cầu thủ 1" trong màn so sánh',
    expected: 'Đúng là cầu thủ vừa chọn từ Lineups, không cần chọn lại',
    priority: 'High',
  },
  {
    id: 'CMP-08',
    category: 'C. US-01 — Chọn cầu thủ',
    title: 'Chọn Cầu thủ 2 từ danh sách đối tượng so sánh',
    precondition: 'Đã có Cầu thủ 1',
    steps: '1. Mở component chọn đối tượng so sánh\n2. Chọn 1 cầu thủ khác làm Cầu thủ 2',
    expected: 'Cầu thủ 2 được chọn đúng, màn so sánh cập nhật hiển thị đầy đủ 2 cầu thủ',
    priority: 'High',
  },

  // ---- D. Phạm vi cầu thủ được phép so sánh ----
  {
    id: 'CMP-09',
    category: 'C. US-01 — Phạm vi cầu thủ',
    title: 'Chỉ cho phép chọn cầu thủ thuộc cùng trận đấu đang xem',
    precondition: 'Đang xem trận A, danh sách chọn Cầu thủ 2',
    steps: '1. Quan sát danh sách cầu thủ có thể chọn làm Cầu thủ 2',
    expected: 'Danh sách CHỈ gồm cầu thủ thuộc trận đấu đang xem (cả 2 đội), không có cầu thủ của trận khác/đội khác không liên quan',
    priority: 'High',
  },
  {
    id: 'CMP-10',
    category: 'C. US-01 — Phạm vi cầu thủ',
    title: 'Cho phép chọn toàn bộ squad hiển thị trên Lineups (cả đá chính và dự bị)',
    precondition: 'Lineups đã hiển thị đủ đội hình chính + danh sách dự bị',
    steps: '1. Kiểm tra danh sách Cầu thủ 2 có bao gồm cả cầu thủ dự bị không, không chỉ 11 cầu thủ đá chính',
    expected: 'Toàn bộ squad hiển thị trên Lineups đều xuất hiện trong danh sách chọn, không giới hạn chỉ đội hình xuất phát',
    priority: 'High',
  },
  {
    id: 'CMP-11',
    category: 'C. US-01 — Phạm vi cầu thủ',
    title: 'Cho phép so sánh cầu thủ đội nhà với cầu thủ đội khách',
    precondition: 'Cầu thủ 1 thuộc đội nhà',
    steps: '1. Chọn Cầu thủ 2 thuộc đội khách',
    expected: 'Cho phép chọn và so sánh bình thường, không bị giới hạn phải cùng đội',
    priority: 'High',
  },
  {
    id: 'CMP-12',
    category: 'C. US-01 — Phạm vi cầu thủ',
    title: 'Không giới hạn so sánh theo vị trí — Tiền đạo vs Tiền đạo',
    precondition: 'Cầu thủ 1 là tiền đạo',
    steps: '1. Chọn Cầu thủ 2 cũng là tiền đạo',
    expected: 'Cho phép so sánh bình thường',
    priority: 'Medium',
  },
  {
    id: 'CMP-13',
    category: 'C. US-01 — Phạm vi cầu thủ',
    title: 'Không giới hạn so sánh theo vị trí — Tiền đạo vs Tiền vệ',
    precondition: 'Cầu thủ 1 là tiền đạo',
    steps: '1. Chọn Cầu thủ 2 là tiền vệ',
    expected: 'Cho phép so sánh bình thường, hiển thị đúng bộ chỉ số tương ứng (xem Business Rule BR02 về vị trí tham chiếu)',
    priority: 'High',
  },
  {
    id: 'CMP-14',
    category: 'C. US-01 — Phạm vi cầu thủ',
    title: 'Không giới hạn so sánh theo vị trí — Tiền đạo vs Hậu vệ',
    precondition: 'Cầu thủ 1 là tiền đạo',
    steps: '1. Chọn Cầu thủ 2 là hậu vệ',
    expected: 'Cho phép so sánh bình thường',
    priority: 'Medium',
  },
  {
    id: 'CMP-15',
    category: 'C. US-01 — Phạm vi cầu thủ',
    title: 'Không giới hạn so sánh theo vị trí — Thủ môn vs Tiền đạo',
    precondition: 'Cầu thủ 1 là thủ môn',
    steps: '1. Chọn Cầu thủ 2 là tiền đạo',
    expected: 'Cho phép so sánh, hiển thị đúng bộ chỉ số nhóm "GK vs FW/MID/DEF" (Minutes Played, Matches Played) thay vì cố ép theo bộ chỉ số GK hoặc FW thuần',
    priority: 'High',
  },

  // ---- E. Nguồn dữ liệu & fallback season ----
  {
    id: 'CMP-16',
    category: 'C. US-01 — Nguồn dữ liệu',
    title: 'Dữ liệu lấy đúng Competition + Season của trận Pre-match đang xem',
    precondition: 'Trận đấu Barcelona vs Real Madrid, La Liga 2025/26 (Upcoming)',
    steps: '1. So sánh Lamine Yamal vs Vinícius Júnior\n2. Đối chiếu số liệu hiển thị với thống kê La Liga 2025/26 thực tế (từ đầu mùa đến hiện tại) qua API/DB',
    expected: 'Số liệu khớp chính xác với La Liga 2025/26 — KHÔNG lẫn dữ liệu từ Champions League hay giải khác mà 2 cầu thủ này cũng tham gia',
    priority: 'High',
  },
  {
    id: 'CMP-17',
    category: 'C. US-01 — Nguồn dữ liệu',
    title: 'Dữ liệu tính đến thời điểm TRƯỚC trận đấu, không bao gồm trận đang xem',
    precondition: 'Trận đấu chưa diễn ra (Pre-match)',
    steps: '1. Đối chiếu tổng số liệu (Goals, xG...) hiển thị với tổng số liệu thực tế TRƯỚC thời điểm kickoff trận này',
    expected: 'Số liệu chỉ tính đến thời điểm trước trận, không có khả năng bị tính dư do trận đang xem (vì trận chưa đá xong/chưa bắt đầu nên về logic sẽ tự đúng — case này ưu tiên verify khi trận chuyển sang live/finished xem dữ liệu so sánh pre-match có bị "rò rỉ" cập nhật theo thời gian thực không)',
    priority: 'Medium',
  },
  {
    id: 'CMP-18',
    category: 'C. US-01 — BR3 Fallback season',
    title: 'BR3: Cầu thủ chưa có dữ liệu season hiện tại → fallback sang season trước gần nhất CÓ dữ liệu (cùng competition)',
    precondition: 'Cầu thủ mới lên đội 1/mới chuyển nhượng, chưa có thống kê ở Competition + Season hiện tại',
    steps: '1. Chọn cầu thủ này để so sánh\n2. Quan sát season nào được dùng để lấy số liệu',
    expected: 'Hệ thống tự động lấy dữ liệu từ season liền trước gần nhất mà cầu thủ CÓ dữ liệu, TRONG CÙNG competition — không tự ý đổi sang competition khác',
    priority: 'High',
  },
  {
    id: 'CMP-19',
    category: 'C. US-01 — BR3 Fallback season',
    title: 'BR3: Không có season nào có dữ liệu (kể cả sau khi fallback) → hiển thị "-"/"N/A"',
    precondition: 'Cầu thủ hoàn toàn chưa từng có dữ liệu thống kê ở competition này (mọi season)',
    steps: '1. Chọn cầu thủ này để so sánh',
    expected: 'Hiển thị "-" hoặc "N/A" cho các chỉ số liên quan, không hiển thị "0" hay dữ liệu rác',
    priority: 'High',
  },
  {
    id: 'CMP-20',
    category: 'C. US-01 — BR3 Fallback season',
    title: 'BR3: Không tự động lấy dữ liệu từ competition khác khi fallback',
    precondition: 'Cầu thủ không có dữ liệu ở Competition A (mọi season) nhưng CÓ dữ liệu ở Competition B (cùng cầu thủ, giải khác)',
    steps: '1. Chọn cầu thủ này để so sánh trong ngữ cảnh trận đấu thuộc Competition A',
    expected: 'Vẫn hiển thị "-"/"N/A" — KHÔNG tự động lấy số liệu từ Competition B dù có sẵn dữ liệu ở đó',
    priority: 'High',
  },

  // ---- F. Thành phần so sánh (US-01) ----
  {
    id: 'CMP-21',
    category: 'C. US-01 — Thành phần hiển thị',
    title: 'Heat maps hiển thị cho cả 2 cầu thủ',
    precondition: 'Đã chọn đủ Cầu thủ 1 và 2',
    steps: '1. Quan sát block Heat maps',
    expected: 'Hiển thị heatmap riêng cho từng cầu thủ, đúng theo Competition + Season đã xác định (bao gồm case đã fallback season)',
    priority: 'Medium',
  },
  {
    id: 'CMP-22',
    category: 'C. US-01 — Thống kê nổi bật',
    title: 'Rating — điểm trung bình mùa giải hiện tại của giải đấu',
    precondition: 'Cả 2 cầu thủ có dữ liệu rating',
    steps: '1. Xem chỉ số Rating của cả 2 cầu thủ',
    expected: 'Đúng điểm rating trung bình mùa giải thuộc giải đấu hiện tại (hoặc season fallback theo BR3)',
    priority: 'High',
  },
  {
    id: 'CMP-23',
    category: 'C. US-01 — Thống kê nổi bật',
    title: 'Goals, xG, Kiến tạo, Thẻ vàng, Thẻ đỏ — đúng tổng số mùa giải',
    precondition: 'Cả 2 cầu thủ có dữ liệu',
    steps: '1. Đối chiếu từng chỉ số (Goals/xG/Assists/Yellow Cards/Red Cards) với dữ liệu backend thực tế của đúng competition+season',
    expected: 'Khớp chính xác từng chỉ số, không lẫn dữ liệu giải/mùa khác',
    priority: 'High',
  },
  {
    id: 'CMP-24',
    category: 'C. US-01 — Thống kê theo vị trí (FW)',
    title: 'Nhóm FW — Total shots, Shots on Target, Shooting Accuracy, Shot on Target/Matches, Goals/Matches, Outside Box Goals',
    precondition: 'Cầu thủ 1 (vị trí tham chiếu theo BR02) là tiền đạo',
    steps: '1. Xem đầy đủ 6 chỉ số nhóm FW\n2. Verify công thức: Shooting Accuracy = (Shots on Target / Total shots) × 100%',
    expected: 'Đủ 6 chỉ số, công thức tính đúng, làm tròn 2 chữ số thập phân cho chỉ số tỷ lệ (theo BR01)',
    priority: 'High',
  },
  {
    id: 'CMP-25',
    category: 'C. US-01 — Thống kê theo vị trí (MID)',
    title: 'Nhóm MID — Total Passes, Pass Accuracy, Accurate Passes/Matches, Key passes, Key pass/Matches, Assists/Matches',
    precondition: 'Cầu thủ 1 (vị trí tham chiếu) là tiền vệ',
    steps: '1. Xem đầy đủ chỉ số nhóm MID\n2. Verify công thức: Pass Accuracy = (Accurate Passes / Total passes) × 100%',
    expected: 'Đủ chỉ số, công thức đúng, làm tròn 2 chữ số thập phân',
    priority: 'High',
  },
  {
    id: 'CMP-26',
    category: 'C. US-01 — Thống kê theo vị trí (DEF)',
    title: 'Nhóm DEF — Total Tackles, Tackle Success Rate, Total Recoveries, Recoveries/Matches, Duels Won %, Blocks/Matches',
    precondition: 'Cầu thủ 1 (vị trí tham chiếu) là hậu vệ',
    steps: '1. Xem đầy đủ chỉ số nhóm DEF\n2. Verify công thức: Tackle Success Rate = (Successful Tackles / Total Tackles) × 100%; Duels Won % = (Duels Won / Duels) × 100%',
    expected: 'Đủ chỉ số, công thức đúng, làm tròn 2 chữ số thập phân',
    priority: 'High',
  },
  {
    id: 'CMP-27',
    category: 'C. US-01 — Thống kê theo vị trí (GK)',
    title: 'Nhóm GK — Total Saves, Save Success Rate, Clean Sheets, Clean Sheet Rate, Goals Conceded',
    precondition: 'Cầu thủ 1 (vị trí tham chiếu) là thủ môn',
    steps: '1. Xem đầy đủ chỉ số nhóm GK\n2. Verify công thức: Save Success Rate = (Total Saves / (Saves + Goals Conceded)) × 100%; Clean Sheet Rate = (Clean Sheets / Matches Played) × 100%',
    expected: 'Đủ chỉ số, công thức đúng, làm tròn 2 chữ số thập phân',
    priority: 'High',
  },
  {
    id: 'CMP-28',
    category: 'C. US-01 — BR02 vị trí tham chiếu',
    title: 'BR02: Vị trí của Cầu thủ 1 là tham chiếu cố định cho bộ chỉ số hiển thị (nhóm FW/MID/DEF)',
    precondition: 'Cầu thủ 1 là hậu vệ (DEF), Cầu thủ 2 là tiền đạo (FW)',
    steps: '1. Quan sát bộ chỉ số hiển thị trong màn so sánh',
    expected: 'Hiển thị đúng bộ chỉ số nhóm DEF (theo vị trí Cầu thủ 1), KHÔNG đổi sang bộ FW dù Cầu thủ 2 là tiền đạo',
    priority: 'High',
  },
  {
    id: 'CMP-29',
    category: 'C. US-01 — Thống kê GK vs khác vị trí',
    title: 'Khi 1 trong 2 người là GK, người còn lại không phải GK → dùng bộ chỉ số "GK vs FW/MID/DEF"',
    precondition: 'Cầu thủ 1 là GK, Cầu thủ 2 là MID (hoặc ngược lại)',
    steps: '1. Quan sát bộ chỉ số hiển thị',
    expected: 'Chỉ hiển thị Minutes Played và Matches Played (theo bảng "GK vs FW/MID/DEF"), không cố hiển thị bộ chỉ số GK đầy đủ lẫn bộ chỉ số kia',
    priority: 'High',
  },
  {
    id: 'CMP-30',
    category: 'C. US-01 — BR01 làm tròn',
    title: 'BR01: Mọi chỉ số dạng tỷ lệ (%) làm tròn đúng 2 chữ số thập phân',
    precondition: 'Có ít nhất 1 chỉ số tỷ lệ với giá trị lẻ nhiều chữ số thập phân trong phép tính gốc',
    steps: '1. Đối chiếu giá trị hiển thị với giá trị tính tay đầy đủ trước khi làm tròn',
    expected: 'Làm tròn chính xác đến 2 chữ số thập phân, không làm tròn theo cách khác (vd cắt bớt/floor thay vì round)',
    priority: 'Medium',
  },

  // ==== US-02: Player vs Team ====

  {
    id: 'CMP-31',
    category: 'D. US-02 — Chọn đối tượng',
    title: 'Chọn cầu thủ từ Lineups + đội bóng đối thủ trong trận hiện tại',
    precondition: 'Đang ở màn hình so sánh, chuyển sang chế độ Player vs Team',
    steps: '1. Cầu thủ lấy từ Lineups (như US-01)\n2. Đối tượng thứ 2 chọn là đội bóng đối thủ',
    expected: 'Chỉ cho phép chọn đúng đội đối thủ trong trận đang xem làm đối tượng so sánh, không phải đội khác',
    priority: 'High',
  },
  {
    id: 'CMP-31B',
    category: 'D. US-02 — Chọn đối tượng',
    title: 'Đội đối thủ được xác định đúng theo chiều Home/Away của cầu thủ đã chọn',
    precondition: 'Test cả 2 chiều: (a) Cầu thủ A thuộc đội Home; (b) Cầu thủ A thuộc đội Away',
    steps: '1. Case (a): chọn cầu thủ A từ đội Home, quan sát đội đối thủ được gán tự động\n2. Case (b): chọn cầu thủ A từ đội Away, quan sát đội đối thủ được gán tự động',
    expected: 'Case (a) → đội đối thủ là đội Away của trận; Case (b) → đội đối thủ là đội Home của trận. Không bao giờ gán nhầm đội đối thủ là chính đội của cầu thủ A',
    priority: 'High',
  },
  {
    id: 'CMP-32',
    category: 'D. US-02 — Case 1 Thành tích đối đầu',
    title: 'Chỉ tính trận cầu thủ đã ra sân (Appearance = phút thi đấu > 0)',
    precondition: 'Cầu thủ A từng có mặt trong đội hình 1 số trận gặp đội B nhưng không ra sân (0 phút)',
    steps: '1. Đối chiếu số liệu đối đầu hiển thị với số trận cầu thủ A thực sự có phút thi đấu > 0 khi gặp đội B',
    expected: 'Các trận cầu thủ A có mặt trong danh sách nhưng KHÔNG thi đấu (0 phút) KHÔNG được tính vào thành tích đối đầu',
    priority: 'High',
  },
  {
    id: 'CMP-33',
    category: 'D. US-02 — Case 1 Thành tích đối đầu',
    title: 'Tính tất cả trận cầu thủ A từng thi đấu cho BẤT KỲ đội nào gặp đội B (không chỉ đội hiện tại)',
    precondition: 'Cầu thủ A từng chơi cho đội C trước đây, đội C đã từng gặp đội B',
    steps: '1. Đối chiếu thành tích đối đầu có bao gồm cả trận cầu thủ A thi đấu cho đội C (đội cũ) gặp đội B không',
    expected: 'Bao gồm toàn bộ lịch sử đối đầu của cầu thủ A với đội B, bất kể lúc đó A thi đấu cho đội nào — đúng theo "Player A trực tiếp thi đấu cho bất kỳ team nào và đối đầu Team B"',
    priority: 'High',
  },
  {
    id: 'CMP-34',
    category: 'D. US-02 — Case 1 Loại trừ trận không hợp lệ',
    title: 'Loại trừ trận giao hữu (Friendly/Pre-season/Exhibition) khỏi thành tích đối đầu',
    precondition: 'Cầu thủ A từng đối đầu đội B trong 1 trận giao hữu',
    steps: '1. Đối chiếu thành tích đối đầu có loại trừ đúng trận giao hữu này không',
    expected: 'Trận giao hữu/Pre-season Friendly/Exhibition/Entertainment match KHÔNG được tính vào thành tích đối đầu, chỉ tính trận đấu thuộc giải đấu chính thức',
    priority: 'High',
  },
  {
    id: 'CMP-35',
    category: 'D. US-02 — Case 1 Chỉ số đối đầu (cầu thủ thường)',
    title: 'Cầu thủ không phải GK — Rating, Goals, Penalty goals, Assists, Cards, Own goals, Missed penalties',
    precondition: 'Cầu thủ A không phải thủ môn',
    steps: '1. Xem đầy đủ các chỉ số đối đầu tổng hợp',
    expected: 'Đủ 7 chỉ số theo đúng bảng spec, không thiếu không thừa. Penalty shootout attempts KHÔNG được tính vào các chỉ số này',
    priority: 'High',
  },
  {
    id: 'CMP-36',
    category: 'D. US-02 — Case 1 Chỉ số đối đầu (thủ môn)',
    title: 'Cầu thủ là GK — thêm Saves, Penalty saves ngoài các chỉ số chung',
    precondition: 'Cầu thủ A là thủ môn',
    steps: '1. Xem đầy đủ các chỉ số đối đầu, kiểm tra có thêm Saves và Penalty saves',
    expected: 'Đủ các chỉ số chung (Rating, Goals, Assists, Cards, Own goals, Missed penalties) + riêng Saves, Penalty saves cho GK',
    priority: 'High',
  },
  {
    id: 'CMP-37',
    category: 'D. US-02 — Case 1 Penalty shootout',
    title: 'Penalty shootout attempts KHÔNG tính vào player match statistics',
    precondition: 'Trong lịch sử đối đầu có ít nhất 1 trận đấu súng luân lưu (penalty shootout)',
    steps: '1. Đối chiếu Penalty goals/Missed penalties hiển thị có loại trừ đúng các quả đá luân lưu không',
    expected: 'Số liệu Penalty goals/Missed penalties KHÔNG bao gồm các lượt đá luân lưu (penalty shootout), chỉ tính penalty trong thời gian thi đấu chính thức',
    priority: 'Medium',
  },
  {
    id: 'CMP-37B',
    category: 'D. US-02 — Case 1 Penalty shootout',
    title: '❗ [CẦN CONFIRM] Saves/Penalty saves của thủ môn — có loại trừ pha cản phá trong loạt sút luân lưu không?',
    precondition: 'Cầu thủ A là thủ môn, trong lịch sử đối đầu có ít nhất 1 trận đi đến loạt sút luân lưu mà A đã cản phá được ít nhất 1 quả',
    steps: '1. Đối chiếu chỉ số Saves/Penalty saves của thủ môn A có bao gồm pha cản phá trong shootout hay không',
    expected: '[CẦN CONFIRM] Spec chỉ nêu rõ "Penalty shootout attempts không tính vào player match statistics" ở dòng Penalty goals/Missed penalties — CHƯA nói rõ Saves/Penalty saves của thủ môn có cùng rule loại trừ này không. Cần PO xác nhận để tránh dev hiểu sai theo 2 hướng khác nhau',
    priority: 'Medium',
  },
  {
    id: 'CMP-38',
    category: 'D. US-02 — Shot maps',
    title: 'Shot maps liệt kê toàn bộ cú sút của player A vs đội B (bỏ phần thời gian)',
    precondition: 'Đã có lịch sử đối đầu với dữ liệu cú sút',
    steps: '1. Xem Shot maps trong màn so sánh Player vs Team\n2. So sánh với shot maps hiện tại của prod (cùng nguồn dữ liệu, chỉ khác hiển thị)',
    expected: 'Liệt kê đủ toàn bộ cú sút của player A khi gặp đội B, giao diện giống shot maps hiện tại của prod NHƯNG không hiển thị thời gian (minute) của mỗi cú sút',
    priority: 'Medium',
  },
  {
    id: 'CMP-39',
    category: 'D. US-02 — Case 2 Rating top 5',
    title: 'Rating trung bình player A vs top 5 rating trung bình của đội B, sort cao→thấp',
    precondition: 'Đội B có ≥ 5 cầu thủ có rating mùa hiện tại',
    steps: '1. Xem block so sánh rating\n2. Kiểm tra danh sách top 5 cầu thủ đội B có đúng sắp xếp giảm dần theo rating trung bình không',
    expected: 'Hiển thị đúng 5 cầu thủ có rating trung bình cao nhất đội B, sắp xếp giảm dần, cạnh rating của player A',
    priority: 'Medium',
  },
  {
    id: 'CMP-40',
    category: 'D. US-02 — Case 2 Đội B có ít hơn 5 cầu thủ đủ điều kiện',
    title: 'Đội B có ít hơn 5 cầu thủ có rating hợp lệ',
    precondition: 'Đội B (ví dụ đội trẻ/mới lên hạng) chỉ có 3 cầu thủ có rating mùa hiện tại',
    steps: '1. Xem block so sánh rating top 5',
    expected: 'Chỉ hiển thị đúng số cầu thủ có dữ liệu thật (3 người), không tạo hàng giả để đủ 5',
    priority: 'Medium',
  },
  {
    id: 'CMP-41',
    category: 'D. US-02 — Case 2 Thống kê nổi bật/vị trí',
    title: 'Case 2: Thống kê nổi bật và theo vị trí của player A vs đội B (dùng chung bảng US-01)',
    precondition: 'Đã xác định vị trí cầu thủ A',
    steps: '1. Xem block thống kê nổi bật/theo vị trí trong chế độ Player vs Team',
    expected: 'Áp dụng đúng công thức và bộ chỉ số như đã định nghĩa ở US-01 (Rating, Goals, xG, Assists, Cards + nhóm theo vị trí FW/MID/DEF/GK)',
    priority: 'Medium',
  },
  {
    id: 'CMP-41B',
    category: 'D. US-02 — Case 2 Thống kê nổi bật/vị trí',
    title: 'Case 2 kế thừa đúng BR3 (fallback season) từ US-01 khi cầu thủ A chưa có dữ liệu season hiện tại',
    precondition: 'Chế độ Player vs Team, cầu thủ A chưa có dữ liệu thống kê competition+season hiện tại (giống điều kiện CMP-18)',
    steps: '1. Xem block "Thống kê nổi bật/theo vị trí" (Case 2) của player A trong chế độ Player vs Team',
    expected: 'Áp dụng đúng BR3: fallback sang season trước gần nhất CÓ dữ liệu cùng competition, hoặc hiển thị "-"/"N/A" nếu không có season nào — spec ghi "Case 2: So sánh thống kê theo mùa giải hiện tại => Theo bảng US-01 ở trên" nên mọi Business Rule của US-01 (BR01, BR02, BR03) đều phải áp dụng nhất quán ở đây, không chỉ áp dụng công thức mà bỏ qua rule fallback',
    priority: 'High',
  },
  {
    id: 'CMP-42',
    category: 'D. US-02 — Heatmap (Pending)',
    title: 'Heat maps Player A vs đội B — đánh dấu Pending theo spec',
    precondition: 'Feature đang trong giai đoạn implement',
    steps: '1. Kiểm tra trạng thái hiển thị Heat maps trong US-02',
    expected: '[GHI CHÚ SPEC] Mục này được đánh dấu "(Pending)" trong AC gốc — cần xác nhận với PO xem đã có trong scope release này chưa trước khi coi thiếu heatmap Player vs Team là bug',
    priority: 'Low',
  },

  // ==== Business Rules chung ====

  {
    id: 'CMP-43',
    category: 'E. BR — Sắp xếp thứ tự hiển thị',
    title: 'Có Confirm Lineup — sắp xếp theo đúng vị trí lineup thật (cả đá chính lẫn dự bị)',
    precondition: 'Trận đấu đã có Confirm Lineup',
    steps: '1. Mở danh sách chọn cầu thủ trong component đối tượng so sánh',
    expected: '11 cầu thủ đá chính sắp xếp theo vị trí ưu tiên dựa theo lineup thật; danh sách dự bị cũng sắp xếp theo vị trí tương tự',
    priority: 'High',
  },
  {
    id: 'CMP-44',
    category: 'E. BR — Sắp xếp thứ tự hiển thị',
    title: 'Chưa Confirm Lineup — sắp xếp theo vị trí ưu tiên mặc định',
    precondition: 'Trận đấu CHƯA có Confirm Lineup',
    steps: '1. Mở danh sách chọn cầu thủ',
    expected: 'Sắp xếp theo đúng thứ tự vị trí ưu tiên: Tiền đạo (Striker, Left Forward, Right Forward) → Tiền vệ (Attacking MF, Centre MF, Defensive MF) → Hậu vệ (Centre Back, Left Back, Right Back) → Thủ môn',
    priority: 'High',
  },
  {
    id: 'CMP-45',
    category: 'E. BR — Sắp xếp thứ tự hiển thị',
    title: 'Cùng vị trí, nhiều cầu thủ → sort theo Rating mùa hiện tại giảm dần',
    precondition: 'Chưa Confirm Lineup, có ≥ 2 cầu thủ cùng 1 vị trí (vd 2 Centre Back)',
    steps: '1. Quan sát thứ tự các cầu thủ cùng vị trí trong danh sách',
    expected: 'Cầu thủ có Rating mùa hiện tại cao hơn xếp trước',
    priority: 'Medium',
  },
  {
    id: 'CMP-46',
    category: 'E. BR — Sắp xếp thứ tự hiển thị',
    title: 'Cùng vị trí VÀ cùng Rating → sort theo Market Value',
    precondition: 'Chưa Confirm Lineup, ≥ 2 cầu thủ cùng vị trí và cùng Rating tuyệt đối',
    steps: '1. Quan sát thứ tự các cầu thủ này',
    expected: 'Cầu thủ có Market Value cao hơn xếp trước',
    priority: 'Low',
  },
  {
    id: 'CMP-47',
    category: 'E. BR — Hiển thị dữ liệu thiếu',
    title: 'Statistic không có dữ liệu → hiển thị "-", KHÔNG hiển thị "0"',
    precondition: 'Cầu thủ có Goals=0 (dữ liệu hợp lệ) và xG không có dữ liệu (thiếu data provider)',
    steps: '1. Xem đồng thời 2 chỉ số Goals và xG của cùng cầu thủ',
    expected: 'Goals hiển thị "0" (vì có dữ liệu hợp lệ, giá trị thật là 0); xG hiển thị "-" (vì không có dữ liệu) — phân biệt rõ 2 trường hợp, không lẫn lộn',
    priority: 'High',
  },
  {
    id: 'CMP-48',
    category: 'E. BR — Case dữ liệu thiếu cụ thể',
    title: 'Case: Tân binh mới lên đội 1, chưa từng thi đấu chính thức',
    precondition: 'Cầu thủ trẻ vừa được đôn lên đội 1, 0 trận đấu chính thức',
    steps: '1. Chọn cầu thủ này để so sánh',
    expected: 'Toàn bộ chỉ số liên quan đến trận đấu hiển thị "-" (không có dữ liệu), không hiển thị "0" gây hiểu nhầm là đã thi đấu nhưng không có thành tích',
    priority: 'Medium',
  },
  {
    id: 'CMP-49',
    category: 'E. BR — Case dữ liệu thiếu cụ thể',
    title: 'Case: Provider thiếu dữ liệu cho 1 chỉ số cụ thể (không phải toàn bộ)',
    precondition: 'Cầu thủ có đủ Goals/Assists nhưng provider không có xG cho giải này',
    steps: '1. Xem đồng thời các chỉ số của cầu thủ này',
    expected: 'Chỉ riêng xG hiển thị "-", các chỉ số khác vẫn hiển thị giá trị thật bình thường — không vì thiếu 1 field mà toàn bộ chỉ số khác cũng bị ẩn',
    priority: 'Medium',
  },

  // ==== F. Edge case số học — chia cho 0 / mẫu số rỗng ====
  {
    id: 'CMP-50',
    category: 'F. Edge case số học',
    title: 'Shooting Accuracy khi Total shots = 0 (tránh chia cho 0)',
    precondition: 'Cầu thủ có Total shots = 0 (chưa từng dứt điểm) nhưng có dữ liệu hợp lệ (đã ra sân)',
    steps: '1. Xem chỉ số Shooting Accuracy (%) = (Shots on Target / Total shots) × 100%',
    expected: 'Không được crash/hiển thị NaN/Infinity — hiển thị "-" hoặc "0%" (cần confirm PO quy ước cụ thể), tuyệt đối không hiển thị lỗi hoặc giá trị vô nghĩa',
    priority: 'High',
  },
  {
    id: 'CMP-51',
    category: 'F. Edge case số học',
    title: 'Pass Accuracy khi Total Passes = 0',
    precondition: 'Cầu thủ vào sân < 1 phút, chưa kịp thực hiện đường chuyền nào',
    steps: '1. Xem chỉ số Pass Accuracy (%)',
    expected: 'Không NaN/Infinity, xử lý nhất quán với quy ước đã chốt ở CMP-50 (cùng 1 rule cho mọi chỉ số tỷ lệ có nguy cơ chia 0)',
    priority: 'High',
  },
  {
    id: 'CMP-52',
    category: 'F. Edge case số học',
    title: 'Tackle Success Rate khi Total Tackles = 0',
    precondition: 'Hậu vệ chưa thực hiện pha tắc bóng nào trong mùa',
    steps: '1. Xem chỉ số Tackle Success Rate (%)',
    expected: 'Không NaN/Infinity, xử lý nhất quán quy ước chia 0',
    priority: 'Medium',
  },
  {
    id: 'CMP-53',
    category: 'F. Edge case số học',
    title: 'Duels Won % khi Duels = 0',
    precondition: 'Cầu thủ chưa tham gia pha tranh chấp tay đôi nào',
    steps: '1. Xem chỉ số Duels Won (%)',
    expected: 'Không NaN/Infinity, xử lý nhất quán quy ước chia 0',
    priority: 'Medium',
  },
  {
    id: 'CMP-54',
    category: 'F. Edge case số học',
    title: 'Save Success Rate khi (Saves + Goals Conceded) = 0',
    precondition: 'Thủ môn mới vào sân, chưa đối mặt cú sút nào (0 saves, 0 goals conceded)',
    steps: '1. Xem chỉ số Save Success Rate (%) = Total Saves / (Saves + Goals Conceded) × 100%',
    expected: 'Mẫu số = 0, không NaN/Infinity — hiển thị "-" (hợp lý hơn "0%" vì đây là "chưa có tình huống nào để đánh giá", không phải "tỷ lệ cứu thua = 0%")',
    priority: 'High',
  },
  {
    id: 'CMP-55',
    category: 'F. Edge case số học',
    title: 'Clean Sheet Rate khi Matches Played = 0',
    precondition: 'Thủ môn có trong squad nhưng Matches Played = 0 (case đã nêu ở CMP-48, xét riêng công thức này)',
    steps: '1. Xem Clean Sheet Rate (%) = Clean Sheets / Matches Played × 100%',
    expected: 'Mẫu số = 0 → hiển thị "-", không hiển thị "0%" (nhất quán với nguyên tắc "không có dữ liệu thì hiển thị -")',
    priority: 'High',
  },
  {
    id: 'CMP-56',
    category: 'F. Edge case số học',
    title: 'Các chỉ số "/Matches Played" khi Matches Played = 0',
    precondition: 'Cầu thủ có Matches Played = 0 nhưng đang test riêng nhóm chỉ số dạng "X / Matches Played" (Goals/Matches, Key pass/Matches, Assists/Matches, Recoveries/Matches, Blocks/Matches)',
    steps: '1. Xem toàn bộ 5 chỉ số dạng "/Matches Played" cho cầu thủ này',
    expected: 'Tất cả đều hiển thị "-" nhất quán, không có chỉ số nào lọt lưới hiển thị "0" hoặc lỗi',
    priority: 'Medium',
  },

  // ==== G. Tương tác giữa các Business Rule (case tổng hợp) ====
  {
    id: 'CMP-57',
    category: 'G. Tương tác Business Rule',
    title: 'Fallback season (BR3) ẢNH HƯỞNG ĐẾN vị trí tham chiếu (BR02) — vị trí lấy theo season nào?',
    precondition: 'Cầu thủ 1 đã fallback sang season trước (theo BR3) do chưa có dữ liệu season hiện tại; season trước cầu thủ này chơi ở vị trí KHÁC với vị trí hiện tại trong Lineup trận đang xem',
    steps: '1. Xác định vị trí tham chiếu (BR02) được lấy từ đâu: vị trí trong Lineup trận đang xem (hiện tại), hay vị trí ghi nhận ở season đã fallback',
    expected: '[CẦN CONFIRM] Spec chưa nêu rõ trường hợp giao thoa 2 rule này — cần chốt: vị trí tham chiếu LUÔN lấy theo Lineup hiện tại (độc lập với việc fallback season để lấy số liệu)',
    priority: 'High',
  },
  {
    id: 'CMP-58',
    category: 'G. Tương tác Business Rule',
    title: 'Sắp xếp theo Rating (BR sắp xếp) khi Rating đang fallback theo season khác (BR3)',
    precondition: 'Trong danh sách sắp xếp theo vị trí, 2 cầu thủ cùng vị trí nhưng 1 người dùng Rating mùa hiện tại, người kia dùng Rating đã fallback (do BR3)',
    steps: '1. Quan sát cách so sánh Rating giữa 2 cầu thủ này để xếp thứ tự',
    expected: '[CẦN CONFIRM] So sánh Rating giữa 2 nguồn khác season có công bằng/hợp lý không, hay cần ưu tiên cầu thủ có dữ liệu season hiện tại đứng trước bất kể Rating',
    priority: 'Medium',
  },
  {
    id: 'CMP-59',
    category: 'G. Tương tác Business Rule',
    title: 'Onboarding (BR1/BR2) hiển thị đồng thời với trạng thái fallback season (BR3) ở lần dùng đầu tiên',
    precondition: 'User lần đầu dùng tính năng, đồng thời cầu thủ 1 đang trong trạng thái fallback season',
    steps: '1. Mở tính năng so sánh lần đầu với cầu thủ có dữ liệu fallback',
    expected: 'Onboarding hiển thị bình thường không bị dữ liệu fallback che khuất/chặn hoặc gây lỗi render đồng thời',
    priority: 'Low',
  },

  // ==== H. UI/UX & tương thích thiết bị ====
  {
    id: 'CMP-60',
    category: 'H. UI/UX & thiết bị',
    title: 'Onboarding hiển thị đúng vị trí trỏ (target) trên các kích thước màn hình khác nhau',
    precondition: 'Test trên ít nhất 2 kích thước màn hình (mobile nhỏ, tablet/desktop lớn)',
    steps: '1. Xem onboarding 4 bước trên từng kích thước màn hình',
    expected: 'Vị trí trỏ vào đúng icon/component tương ứng ở mọi kích thước, không bị lệch/che khuất nội dung khác',
    priority: 'Medium',
  },
  {
    id: 'CMP-61',
    category: 'H. UI/UX & thiết bị',
    title: 'Tên cầu thủ/đội bóng dài bị cắt/xuống dòng hợp lý trong bảng so sánh',
    precondition: 'Chọn cầu thủ có tên đầy đủ dài (vd tên có nhiều thành phần)',
    steps: '1. Xem cách hiển thị tên trong header bảng so sánh',
    expected: 'Không bị tràn layout, vỡ giao diện; có xử lý truncate/wrap hợp lý',
    priority: 'Low',
  },
  {
    id: 'CMP-62',
    category: 'H. UI/UX & thiết bị',
    title: 'Đổi Cầu thủ 2 nhiều lần liên tiếp — dữ liệu không bị lẫn/giật giữa các lần đổi',
    precondition: 'Đang so sánh Cầu thủ 1 vs Cầu thủ 2 (A)',
    steps: '1. Đổi nhanh liên tiếp sang Cầu thủ 2 (B), rồi (C), rồi (D) trong thời gian ngắn',
    expected: 'Dữ liệu hiển thị cuối cùng đúng là của cầu thủ (D) — không bị race condition hiển thị nhầm dữ liệu của (B) hoặc (C) do response API trả về không đúng thứ tự',
    priority: 'Medium',
  },
  {
    id: 'CMP-63',
    category: 'H. UI/UX & thiết bị',
    title: 'Đóng popup so sánh rồi mở lại — giữ đúng lựa chọn cũ hay reset',
    precondition: 'Đã chọn Cầu thủ 1 + Cầu thủ 2, đóng popup so sánh',
    steps: '1. Mở lại popup so sánh (vẫn trong cùng phiên xem trận, chưa rời trang)',
    expected: '[CẦN CONFIRM] Giữ nguyên lựa chọn cũ hay reset về trạng thái ban đầu (chỉ có Cầu thủ 1 mặc định từ Lineups)?',
    priority: 'Low',
  },

  // ==== I. Case đặc thù bóng đá (domain-specific) ====
  {
    id: 'CMP-64',
    category: 'I. Case đặc thù bóng đá',
    title: 'So sánh 2 cầu thủ đang cho mượn (loan) từ 2 CLB khác nhau, cùng thi đấu ở giải hiện tại',
    precondition: 'Cả 2 cầu thủ đều đang cho mượn tại đội trong trận đang xem',
    steps: '1. So sánh 2 cầu thủ này',
    expected: 'Dữ liệu lấy đúng theo đội ĐANG cho mượn tới (đội hiện tại thi đấu ở giải này), không lấy nhầm dữ liệu của đội chủ quản',
    priority: 'Medium',
  },
  {
    id: 'CMP-65',
    category: 'I. Case đặc thù bóng đá',
    title: 'Cầu thủ chuyển nhượng giữa mùa — dữ liệu trước và sau chuyển nhượng trong CÙNG competition có được cộng dồn không',
    precondition: 'Cầu thủ chuyển từ CLB X sang CLB Y giữa mùa giải, cả X và Y đều thi đấu cùng 1 giải (competition) hiện tại',
    steps: '1. Đối chiếu tổng số liệu (Goals, Matches...) hiển thị có cộng dồn cả giai đoạn ở CLB X lẫn CLB Y trong cùng competition + season không',
    expected: '[CẦN CONFIRM] Xác nhận với PO: số liệu tính theo CẦU THỦ trong competition+season (cộng dồn cả 2 CLB), hay chỉ tính từ khi cầu thủ gia nhập đội hiện tại',
    priority: 'High',
  },
  {
    id: 'CMP-66',
    category: 'I. Case đặc thù bóng đá',
    title: 'Trận đấu Pre-match nhưng đã có lineup dự kiến (chưa confirm) — Cầu thủ 1 chọn từ lineup dự kiến này',
    precondition: 'Lineup ở trạng thái dự kiến/probable, chưa chính thức confirm (khác với case CMP-43/44 chỉ nói về sắp xếp thứ tự)',
    steps: '1. Chọn 1 cầu thủ từ lineup dự kiến để làm Cầu thủ 1\n2. Sau đó lineup chính thức được confirm và cầu thủ này KHÔNG có trong đội hình chính thức (bị loại phút chót)',
    expected: '[CẦN CONFIRM] Popup so sánh đã mở trước đó có cần cập nhật/cảnh báo gì không khi lineup thực tế thay đổi so với lúc user bắt đầu so sánh?',
    priority: 'Low',
  },
  {
    id: 'CMP-67',
    category: 'I. Case đặc thù bóng đá',
    title: 'Giải đấu theo thể thức Cup/Playoff — "từ đầu mùa" tính từ vòng nào',
    precondition: 'Trận đấu thuộc giải Cup có nhiều vòng loại trực tiếp (không phải giải vòng tròn)',
    steps: '1. Xác nhận "từ đầu mùa giải" trong ngữ cảnh Cup nghĩa là từ trận đầu tiên của cầu thủ trong toàn bộ mùa giải đó (tính cả vòng loại), hay chỉ từ vòng hiện tại',
    expected: '[CẦN CONFIRM] Cần làm rõ định nghĩa "season" áp dụng thế nào với thể thức Cup/Playoff nhiều vòng, khác giải vòng tròn thông thường',
    priority: 'Medium',
  },
  {
    id: 'CMP-68',
    category: 'I. Case đặc thù bóng đá',
    title: 'US-02: Đội B là đội mới lên hạng, chưa từng gặp cầu thủ A trong lịch sử',
    precondition: 'Đội B mới thăng hạng, chưa từng đối đầu với bất kỳ đội nào cầu thủ A từng khoác áo',
    steps: '1. Chọn Player vs Team với đội B trong tình huống này',
    expected: 'Hiển thị trạng thái "không có dữ liệu đối đầu" rõ ràng (vd "-" hoặc empty state có thông báo), không hiển thị lỗi hoặc bảng trống không giải thích',
    priority: 'Medium',
  },
  {
    id: 'CMP-69',
    category: 'I. Case đặc thù bóng đá',
    title: 'US-02: Cầu thủ A và đội B đối đầu RẤT NHIỀU lần trong lịch sử (câu lạc bộ lâu đời, nhiều mùa giải)',
    precondition: 'Cầu thủ kỳ cựu, đối đầu đội B hàng chục lần qua nhiều năm/nhiều CLB khác nhau',
    steps: '1. Xem hiệu năng tải trang và độ chính xác tổng hợp số liệu với tập dữ liệu lớn',
    expected: 'Trang tải hợp lý (không timeout/lag), số liệu tổng hợp (Goals, Assists, Cards...) vẫn chính xác dù cộng dồn từ nhiều trận/nhiều đội khác nhau trong sự nghiệp',
    priority: 'Low',
  },
];

const openQuestions = [
  { stt: 1, cauHoi: 'CMP-05: Khi user thoát onboarding giữa chừng (mới xem 2/4 bước), lần mở lại có tiếp tục từ bước dở dang, phát lại từ đầu, hay coi như đã xem và không hiện nữa?' },
  { stt: 2, cauHoi: 'CMP-42: Heat maps cho Player vs Team được spec đánh dấu "(Pending)" — đã có trong scope release lần này chưa, hay để dành cho phase sau?' },
  { stt: 3, cauHoi: 'US-01 BR3 fallback season: nếu season liền trước gần nhất CŨNG không đủ dữ liệu (ví dụ cầu thủ mới chuyển tới giải này 1 mùa, mùa trước đó chơi giải khác), có tiếp tục fallback lùi thêm season nữa hay dừng lại và hiển thị "-" ngay?' },
  { stt: 4, cauHoi: 'CMP-40: Đội B có ít hơn 5 cầu thủ đủ điều kiện rating — có cần hiển thị thông báo/ghi chú gì cho user biết lý do danh sách ngắn hơn 5 không, hay chỉ hiển thị đúng số lượng thật là đủ?' },
  { stt: 5, cauHoi: 'CMP-38 Shot maps: "làm tương tự shot maps hiện tại của prod" — cần xác nhận rõ prod hiện tại đang ở đâu (link tham chiếu cụ thể) để design/dev/QA dùng chung 1 baseline.' },
  { stt: 6, cauHoi: 'Khi Cầu thủ 1 chuyển đổi vị trí thi đấu tuỳ trận (ví dụ vừa đá tiền vệ vừa đá hậu vệ tuỳ giải), vị trí "tham chiếu" theo BR02 lấy từ đâu — vị trí trong lineup trận đang xem, hay vị trí chính (primary position) của cầu thủ?' },
  { stt: 7, cauHoi: 'CMP-57: Khi cầu thủ đã fallback season (BR3) để lấy số liệu, vị trí tham chiếu (BR02) lấy theo Lineup hiện tại hay theo vị trí ghi nhận ở season đã fallback? Cần chốt rule ưu tiên khi 2 Business Rule giao thoa.' },
  { stt: 8, cauHoi: 'CMP-50 → CMP-56: Quy ước hiển thị khi mẫu số = 0 trong công thức tỷ lệ (Shooting Accuracy, Pass Accuracy, Tackle Success Rate...) — hiển thị "-" hay "0%"? Cần 1 quy tắc thống nhất áp dụng cho TẤT CẢ chỉ số dạng tỷ lệ, tránh mỗi chỉ số xử lý 1 kiểu khác nhau.' },
  { stt: 9, cauHoi: 'CMP-65: Cầu thủ chuyển nhượng giữa mùa (cùng competition, khác CLB) — số liệu tổng hợp hiển thị có cộng dồn cả giai đoạn ở CLB cũ và CLB mới không, hay chỉ tính từ khi gia nhập đội hiện tại?' },
  { stt: 10, cauHoi: 'CMP-67: Với giải đấu thể thức Cup/Playoff (nhiều vòng loại trực tiếp, không phải vòng tròn), "từ đầu mùa giải" được tính từ đâu — vòng đầu tiên của mùa giải đó, hay có định nghĩa khác?' },
  { stt: 11, cauHoi: 'CMP-63: Đóng popup so sánh rồi mở lại trong cùng phiên xem trận — giữ nguyên lựa chọn Cầu thủ 2 đã chọn trước đó, hay reset về mặc định (chỉ có Cầu thủ 1 từ Lineups)?' },
  { stt: 12, cauHoi: 'CMP-37B: Saves/Penalty saves của thủ môn trong US-02 Case 1 — có loại trừ pha cản phá trong loạt sút luân lưu (penalty shootout) giống như Penalty goals/Missed penalties không? Spec chỉ nêu rõ rule loại trừ cho 2 chỉ số đó, chưa nhắc đến Saves.' },
  { stt: 13, cauHoi: 'CMP-41B: US-02 Case 2 ghi "So sánh thống kê theo mùa giải hiện tại => Theo bảng US-01 ở trên" — xác nhận điều này nghĩa là mọi Business Rule của US-01 (BR01 làm tròn, BR02 vị trí tham chiếu, BR03 fallback season) đều áp dụng nguyên vẹn cho Case 2, không chỉ riêng công thức tính?' },
];

test.describe('[TASK-3575] Export bộ test case (Excel) — không phải test verify', () => {
  test('Xuất TESTCASE_ComparePlayer_Lineup.xlsx', async () => {
    const sheets: ExcelSheetSpec[] = [
      {
        name: 'Tổng quan',
        columns: [
          { header: 'Thông tin', key: 'k', width: 28 },
          { header: 'Nội dung', key: 'v', width: 95 },
        ],
        rows: [
          { k: 'Task', v: 'TASK 3575 — [App|Web][Football][Lineup - Player Pop up] So sánh cầu thủ trước trận' },
          { k: 'Breadcrumb', v: 'Pre-Match → Details → Lineups → Select any player → Show pop-up player details → Select icon compare' },
          { k: 'User Story', v: 'US-01: Player vs Player | US-02: Player vs Team' },
          { k: 'Trạng thái tại thời điểm viết', v: 'Feature chưa lên staging — dùng để QA test tay khi feature deploy' },
          { k: 'Tổng số test case', v: String(TEST_CASES.length) },
          { k: 'Số câu hỏi mở cần confirm', v: String(openQuestions.length) },
        ],
        wrapText: true,
      },
      {
        name: 'Test Cases',
        columns: [
          { header: 'ID', key: 'id', width: 10 },
          { header: 'Category', key: 'category', width: 32 },
          { header: 'Tiêu đề', key: 'title', width: 48 },
          { header: 'Precondition', key: 'precondition', width: 48 },
          { header: 'Steps', key: 'steps', width: 55 },
          { header: 'Expected Result', key: 'expected', width: 65 },
          { header: 'Priority', key: 'priority', width: 12 },
          { header: 'Status', key: 'status', width: 14 },
        ],
        rows: TEST_CASES.map((r) => ({ ...r, status: 'Not run' })),
        wrapText: true,
      },
      {
        name: 'Câu hỏi mở',
        columns: [
          { header: 'STT', key: 'stt', width: 8 },
          { header: 'Câu hỏi cần confirm dev/PO', key: 'cauHoi', width: 110 },
          { header: 'Câu trả lời', key: 'answer', width: 50 },
        ],
        rows: openQuestions.map((q) => ({ ...q, answer: '' })),
        wrapText: true,
      },
    ];

    await saveExcelForSeason(SEASON_DIR, SLUG, 'TESTCASE_ComparePlayer_Lineup.xlsx', sheets);
  });
});
