// Danh sách coach ref_id dùng để test task 3369 — quét từ Mongo matches (đủ 91
// trận, ~5 ngày trước tới 7 ngày sau thời điểm quét) qua mapping_matches ->
// encode -> GET /football/event/{id}/lineups lấy home.coach/away.coach.id.
// 16 coach đầu (finished + not_started) được chọn tay từ trước, giữ nguyên để
// không mất tính đa dạng trạng thái trận; 100 coach còn lại lấy từ quét diện
// rộng (chủ yếu finished — dataset Mongo tại thời điểm quét không có live).
export type CoachSample = { name: string; refId: string; matchStatus: string; matchLabel: string };

export const COACHES: CoachSample[] = [
  { name: 'Sebastián Abreu', refId: 'mfiws1aovdasdxd', matchStatus: 'finished', matchLabel: 'Tijuana vs Cruz Azul' },
  { name: 'Héctor Cárdenas', refId: 'b1ta1llsfk1rbib', matchStatus: 'finished', matchLabel: '(profile mẫu ban đầu)' },
  { name: 'Dorival Júnior', refId: 'jy2us9towvsn7fj', matchStatus: 'finished', matchLabel: 'Sao Paulo vs Coritiba' },
  { name: 'Fernando Seabra', refId: '54cvbml0sv2rl7t', matchStatus: 'finished', matchLabel: 'Sao Paulo vs Coritiba' },
  { name: 'Walter Ribonetto', refId: 'g38gsxoovxsrl7t', matchStatus: 'finished', matchLabel: 'Everton CD vs Audax Italiano' },
  { name: 'Patricio Graff', refId: 'jqcfxzpo3eosdt6', matchStatus: 'finished', matchLabel: 'Everton CD vs Audax Italiano' },
  { name: 'Paúl Vélez', refId: 's4luxy1o8djrihp', matchStatus: 'finished', matchLabel: 'Mushuc Runa vs Barcelona SC ECU' },
  { name: 'Pablo Trobbiani', refId: '9zuz9plsm46ni6u', matchStatus: 'finished', matchLabel: 'Mushuc Runa vs Barcelona SC ECU' },
  { name: 'Ronald Fuentes', refId: 'jz5xx7no1l0rbib', matchStatus: 'finished', matchLabel: 'Union Espanola vs San Marcos Arica' },
  { name: 'Iván Endre', refId: '9zuz9plng3oni6u', matchStatus: 'finished', matchLabel: 'Union Espanola vs San Marcos Arica' },
  { name: 'Jonatan Alba', refId: 'q69zrnl5w4jrah5', matchStatus: 'not_started', matchLabel: 'Rostov vs Lokomotiv Moscow' },
  { name: 'Mikhail Galaktionov', refId: 'h5bhxp8o2lnr35v', matchStatus: 'not_started', matchLabel: 'Rostov vs Lokomotiv Moscow' },
  { name: 'Christoffer Andersson', refId: '1z88sr5ovwbntsd', matchStatus: 'not_started', matchLabel: 'IFK Skovde vs Falkenberg' },
  { name: 'Christopher Lock', refId: 'o8tzjglkh3js006', matchStatus: 'not_started', matchLabel: 'Charlton Ath U21 vs Bolton U21' },
  { name: 'Vladan Milojevic', refId: 'm2q3xlro9ogn2ed', matchStatus: 'not_started', matchLabel: 'Shanghai Shenhua vs Beijing Guoan' },
  { name: 'Nick Montgomery', refId: 'mfiws1ao2yosdxd', matchStatus: 'not_started', matchLabel: 'Shanghai Shenhua vs Beijing Guoan' },
  { name: "Chris O'Neal", refId: 'b1ta1lls9lbrbib', matchStatus: 'postponed', matchLabel: 'Huntsville City vs Crown Legacy' },
  { name: 'Kevin Sawchak', refId: 'o6jamrlu8ygs3t6', matchStatus: 'postponed', matchLabel: 'Huntsville City vs Crown Legacy' },
  { name: 'Martín Leva', refId: '1ztvu6le7gbr5s2', matchStatus: 'finished', matchLabel: 'Atenas vs Kimberley Mar del Plata' },
  { name: 'Matt Glaeser', refId: '7xdat6l5mxgr35v', matchStatus: 'finished', matchLabel: 'Forward Madison vs Greenville Triumph' },
  { name: 'Dave Dixon', refId: '54cvbml68wyrl7t', matchStatus: 'finished', matchLabel: 'Forward Madison vs Greenville Triumph' },
  { name: 'Rudolf Mozr', refId: '7kbz8il8mprn5ek', matchStatus: 'finished', matchLabel: 'Tiga Sport vs Auckland City' },
  { name: 'Matías Almeyda', refId: '2es0s3ko2wgntnv', matchStatus: 'finished', matchLabel: 'Monterrey vs Nashville' },
  { name: 'B.J. Callaghan', refId: 'b1ta1llso1nrbib', matchStatus: 'finished', matchLabel: 'Monterrey vs Nashville' },
  { name: 'Christian Corrales', refId: 'bm0nxitoo4gs3t6', matchStatus: 'finished', matchLabel: 'San Martin Mendoza vs Sol de Mayo' },
  { name: 'Mario Martínez', refId: 'hesv5ylk123sdxd', matchStatus: 'finished', matchLabel: 'San Martin Mendoza vs Sol de Mayo' },
  { name: 'Omar Larroza', refId: '6hqac9l349grihp', matchStatus: 'finished', matchLabel: 'Sarmiento LB vs Sol de America' },
  { name: 'Juan José Luvera', refId: 'mfiws1ao3lmsdxd', matchStatus: 'finished', matchLabel: 'San Marcos Arica vs Union San Felipe' },
  { name: 'Luis Marcoleta', refId: 'ym2xwfio0n6s006', matchStatus: 'finished', matchLabel: 'Antofagasta vs Santiago Wanderers' },
  { name: 'Francisco Palladino', refId: 'no03wnpoe84rah5', matchStatus: 'finished', matchLabel: 'Antofagasta vs Santiago Wanderers' },
  { name: 'Artur Jorge', refId: 'c9dxsq8owjhr5s2', matchStatus: 'finished', matchLabel: 'Cruzeiro vs Flamengo' },
  { name: 'Leonardo Jardim', refId: 'g38gsxoow90rl7t', matchStatus: 'finished', matchLabel: 'Cruzeiro vs Flamengo' },
  { name: 'Carlos Llamosa', refId: 'b44vv3l2xybntsd', matchStatus: 'finished', matchLabel: 'San Antonio vs Miami FC' },
  { name: 'Gastón Maddoni', refId: 'sybadnl4l16sdt6', matchStatus: 'finished', matchLabel: 'San Antonio vs Miami FC' },
  { name: 'Javier Lopez', refId: '87dyw5rodgbni6u', matchStatus: 'finished', matchLabel: 'CD Motagua vs Cartagines SA' },
  { name: 'Amarini Villatoro', refId: 'jy2us9toh7on7fj', matchStatus: 'finished', matchLabel: 'CD Motagua vs Cartagines SA' },
  { name: 'Alan McCann', refId: '623z28l1f75rt8p', matchStatus: 'finished', matchLabel: 'Spokane Velocity vs Colorado Springs' },
  { name: 'Rafael Dudamel', refId: '2l31xgoodkhsjyf', matchStatus: 'postponed', matchLabel: 'Dep. Cali vs Atl. Nacional' },
  { name: 'Lucas González Vélez', refId: 'h5bhxp8oxjyr35v', matchStatus: 'postponed', matchLabel: 'Dep. Cali vs Atl. Nacional' },
  { name: 'Antonio Mohamed', refId: 'jz5xx7nomvnrbib', matchStatus: 'finished', matchLabel: 'Toluca vs FC Dallas' },
  { name: 'Eric Quill', refId: '6hqac9ld970rihp', matchStatus: 'finished', matchLabel: 'Toluca vs FC Dallas' },
  { name: 'Mikey Varas', refId: 'm2q3xlrod29n2ed', matchStatus: 'finished', matchLabel: 'San Diego vs Puebla' },
  { name: 'Gerardo Espinoza', refId: '2wogs0ko7yrs1xj', matchStatus: 'finished', matchLabel: 'San Diego vs Puebla' },
  { name: 'Brian Schmetzer', refId: '2l31xgoo1v9sjyf', matchStatus: 'finished', matchLabel: 'Seattle Sounders vs Chivas Guadalajara' },
  { name: 'Gabriel Milito', refId: 'ym2xwfio2x0s006', matchStatus: 'finished', matchLabel: 'Seattle Sounders vs Chivas Guadalajara' },
  { name: 'Marc Dos Santos', refId: 'c9dxsq8o17nr5s2', matchStatus: 'finished', matchLabel: 'Los Angeles FC vs Queretaro' },
  { name: 'Esteban González', refId: 'mx7a61lsx0ose70', matchStatus: 'finished', matchLabel: 'Los Angeles FC vs Queretaro' },
  { name: 'Jorge Rodríguez', refId: 's4luxy1oxxgrihp', matchStatus: 'finished', matchLabel: 'CD FAS vs Hankook Verdes' },
  { name: 'Otar Gagnidze', refId: '1ztvu6l709ar5s2', matchStatus: 'finished', matchLabel: 'Dinamo Tbilisi II vs Iberia Tbilisi 2010' },
  { name: 'Anvar Gofurov', refId: 'b44vv3l0rg7ntsd', matchStatus: 'finished', matchLabel: 'Termez Surkhon vs Sogdiana Jizak' },
  { name: 'Ulugbek Bakaev', refId: 'mfiws1aoxz8sdxd', matchStatus: 'finished', matchLabel: 'Termez Surkhon vs Sogdiana Jizak' },
  { name: 'Islam Akhmedov', refId: '7kbz8ilw7lon5ek', matchStatus: 'finished', matchLabel: 'FK Andijon vs Neftchi Fargona' },
  { name: 'Islom Ismoilov', refId: 'o8tzjglu867s006', matchStatus: 'finished', matchLabel: 'FK Andijon vs Neftchi Fargona' },
  { name: 'Miroslav Romashchenko', refId: 's5ofw4ko0yon5ek', matchStatus: 'finished', matchLabel: 'Tobol Kostanai vs Partizan' },
  { name: 'Sasa Ilic', refId: 'jy2us9to0jgn7fj', matchStatus: 'finished', matchLabel: 'Tobol Kostanai vs Partizan' },
  { name: 'Aleksandr Khomyakov', refId: '87dyw5roxlcni6u', matchStatus: 'finished', matchLabel: 'Buxoro FK vs OKMK Olmaliq' },
  { name: 'Mirdzhalol Kasymov', refId: 'ym2xwfiolxbs006', matchStatus: 'finished', matchLabel: 'Buxoro FK vs OKMK Olmaliq' },
  { name: 'Craig Hill', refId: '270vqal412ss6pk', matchStatus: 'finished', matchLabel: 'Edustus IPS vs Kultsu Lpr' },
  { name: 'Konstantin Vassiljev', refId: 'mx7a61l650zse70', matchStatus: 'finished', matchLabel: 'Flora Tallinn vs Inter Escaldes' },
  { name: 'Otger Canals', refId: '54cvbml01yorl7t', matchStatus: 'finished', matchLabel: 'Flora Tallinn vs Inter Escaldes' },
  { name: 'Jiri Koski', refId: 'n97akml3fxzsjyf', matchStatus: 'finished', matchLabel: 'PPJ Akatemia vs Mypa' },
  { name: 'Miika Kuntonen', refId: '1z88sr5o7pyntsd', matchStatus: 'finished', matchLabel: 'PPJ Akatemia vs Mypa' },
  { name: 'Joni Lehtonen', refId: 'o014smco83zs6pk', matchStatus: 'finished', matchLabel: 'Ilves Tampere vs Rijeka' },
  { name: 'Matjaz Kek', refId: 'jqcfxzpo915sdt6', matchStatus: 'finished', matchLabel: 'Ilves Tampere vs Rijeka' },
  { name: 'Qurban Qurbanov', refId: '2wogs0ko873s1xj', matchStatus: 'finished', matchLabel: 'Qarabag vs Dynamo Kyiv' },
  { name: 'Igor Kostyuk', refId: 'o8tzjgl7m8cs006', matchStatus: 'finished', matchLabel: 'Qarabag vs Dynamo Kyiv' },
  { name: 'Damir Buric', refId: 'h5bhxp8ol31r35v', matchStatus: 'finished', matchLabel: 'Abha vs Al-Hazm' },
  { name: 'Jalel Kadri', refId: 'm2q3xlro84nn2ed', matchStatus: 'finished', matchLabel: 'Abha vs Al-Hazm' },
  { name: 'Viktors Morozs', refId: '2l31xgoo64gsjyf', matchStatus: 'finished', matchLabel: 'Rigas FS vs Baumit Jablonec' },
  { name: 'Lubos Kozel', refId: 'y3d7s6do3z9rq93', matchStatus: 'finished', matchLabel: 'Rigas FS vs Baumit Jablonec' },
  { name: 'Filipe Coelho', refId: 'jqcfxzpor67sdt6', matchStatus: 'finished', matchLabel: 'Univ Craiova vs KuPs' },
  { name: 'Miika Nuutinen', refId: '87dyw5rol99ni6u', matchStatus: 'finished', matchLabel: 'Univ Craiova vs KuPs' },
  { name: 'Henning Berg', refId: 'g38gsxoo84zrl7t', matchStatus: 'finished', matchLabel: 'Omonia Nicosia vs Lincoln Red Imps' },
  { name: 'Juan Pavón', refId: '623z28lvhjqrt8p', matchStatus: 'finished', matchLabel: 'Omonia Nicosia vs Lincoln Red Imps' },
  { name: 'Mike Tullberg', refId: 'no03wnpoowqrah5', matchStatus: 'finished', matchLabel: 'Midtjylland vs Bohemians' },
  { name: 'Alan Reynolds', refId: '7au4xbkownmr31c', matchStatus: 'finished', matchLabel: 'Midtjylland vs Bohemians' },
  { name: 'Jens Olsen', refId: 'jz5xx7noe1mrbib', matchStatus: 'finished', matchLabel: 'Nordsjaelland vs Valur Reykjavik' },
  { name: 'Hermann Hreidarsson', refId: 's4luxy1o0j8rihp', matchStatus: 'finished', matchLabel: 'Nordsjaelland vs Valur Reykjavik' },
  { name: 'Branislav Fodrek', refId: 'ym2xwfio700s006', matchStatus: 'finished', matchLabel: 'Dunajska Streda vs Twente' },
  { name: 'John van den Brom', refId: 'mfiws1ao7xcsdxd', matchStatus: 'finished', matchLabel: 'Dunajska Streda vs Twente' },
  { name: 'Aleksandr Shagoyko', refId: '5z3v0bl1fg7rq93', matchStatus: 'finished', matchLabel: 'Dinamo Minsk vs Sporting Braga' },
  { name: 'Carlos Vicens', refId: '2wogs0kose6s1xj', matchStatus: 'finished', matchLabel: 'Dinamo Minsk vs Sporting Braga' },
  { name: 'Jørgen Vik', refId: 'no03wnpowg5rah5', matchStatus: 'finished', matchLabel: 'Tromso IL vs CFR Cluj' },
  { name: 'António Folha', refId: 'ym2xwfiotx1s006', matchStatus: 'finished', matchLabel: 'Tromso IL vs CFR Cluj' },
  { name: 'Filipp Sokolinskiy', refId: 'o8tzjglu4v2s006', matchStatus: 'finished', matchLabel: 'BC Maxline vs Borac Banja Luka' },
  { name: 'Vinko Marinovic', refId: 'neo1xasom4jr6iv', matchStatus: 'finished', matchLabel: 'BC Maxline vs Borac Banja Luka' },
  { name: 'Henrik Rydström', refId: 's5ofw4komgan5ek', matchStatus: 'finished', matchLabel: 'Hammarby vs Rakow Czestochowa' },
  { name: 'Dawid Kroczek', refId: 's5ofw4ko3gon5ek', matchStatus: 'finished', matchLabel: 'Hammarby vs Rakow Czestochowa' },
  { name: 'Vincenzo Italiano', refId: 'jy2us9to1yrn7fj', matchStatus: 'finished', matchLabel: 'Besiktas vs Hradec Kralove' },
  { name: 'David Horejs', refId: 'c9dxsq8o8vqr5s2', matchStatus: 'finished', matchLabel: 'Besiktas vs Hradec Kralove' },
  { name: 'Michal Gasparik', refId: 's5ofw4ko744n5ek', matchStatus: 'finished', matchLabel: 'Gornik Zabrze vs Ferencvaros' },
  { name: 'Balázs Borbély', refId: '270vqal4m4gs6pk', matchStatus: 'finished', matchLabel: 'Gornik Zabrze vs Ferencvaros' },
  { name: 'Clementine Toure', refId: 'jy2us9to8dcn7fj', matchStatus: 'finished', matchLabel: 'Ivory Coast (W) vs Ghana (W)' },
  { name: 'Yusif Basigi', refId: 'mfiws1aoo42sdxd', matchStatus: 'finished', matchLabel: 'Ivory Coast (W) vs Ghana (W)' },
  { name: 'Sölvi Ottesen', refId: 'gk7aeql13kcr6iv', matchStatus: 'finished', matchLabel: 'Vikingur Reykjavik vs Thun' },
  { name: 'Gian Luca Privitelli', refId: 'y3d7s6do5o0rq93', matchStatus: 'finished', matchLabel: 'Vikingur Reykjavik vs Thun' },
  { name: 'Marc Schneider', refId: 'm2q3xlrof52n2ed', matchStatus: 'finished', matchLabel: 'Vaduz vs Inter Turku' },
  { name: 'Vesa Vasara', refId: '2wogs0kofj6s1xj', matchStatus: 'finished', matchLabel: 'Vaduz vs Inter Turku' },
  { name: 'Sigurdur Ragnar Eyjólfsson', refId: 'y3d7s6dolvgrq93', matchStatus: 'finished', matchLabel: 'NSI Runavik vs Lugano' },
  { name: 'Mattia Croci-Torti', refId: 'bm0nxito976s3t6', matchStatus: 'finished', matchLabel: 'NSI Runavik vs Lugano' },
  { name: 'Jón Óli Daníelsson', refId: '1z88sr5o40sntsd', matchStatus: 'finished', matchLabel: 'IBV Vestmannaeyjar (W) vs Stjarnan (W)' },
  { name: 'Patrick De Wilde', refId: 'jy2us9tovnon7fj', matchStatus: 'finished', matchLabel: 'KFR Aegir vs Volsungur' },
  { name: 'Ray Jónsson', refId: '5z3v0bl06zcrq93', matchStatus: 'finished', matchLabel: 'Grindavik vs Throttur Reykjavik' },
  { name: 'Sigurvin Ólafsson', refId: 's5ofw4kogghn5ek', matchStatus: 'finished', matchLabel: 'Grindavik vs Throttur Reykjavik' },
  { name: 'Daniel Osafo-Badu', refId: 'q69zrnl6w82rah5', matchStatus: 'finished', matchLabel: 'Vestri vs IR Reykjavik' },
  { name: 'Jóhann Gudmundsson', refId: 'o8tzjgl11ers006', matchStatus: 'finished', matchLabel: 'Vestri vs IR Reykjavik' },
  { name: 'Thomas Letsch', refId: 'y3d7s6dovzzrq93', matchStatus: 'finished', matchLabel: 'Al-Shabab vs Al-Qadasiya' },
  { name: 'Brendan Rodgers', refId: 'm2q3xlro959n2ed', matchStatus: 'finished', matchLabel: 'Al-Shabab vs Al-Qadasiya' },
  { name: 'Bruno Lage', refId: 'neo1xasoml7r6iv', matchStatus: 'finished', matchLabel: 'Al-Draih vs Al-Ahli SFC' },
  { name: 'Marino Pusic', refId: 'ym2xwfio0ess006', matchStatus: 'finished', matchLabel: 'Al-Draih vs Al-Ahli SFC' },
  { name: 'Ardijan Nuhiji', refId: 'bm0nxito530s3t6', matchStatus: 'finished', matchLabel: 'Drita vs Tre Fiori' },
  { name: 'Danilo Girolomoni', refId: 'mx7a61lsfncse70', matchStatus: 'finished', matchLabel: 'Drita vs Tre Fiori' },
  { name: 'Festim Ademi', refId: '5z3v0blu60yrq93', matchStatus: 'finished', matchLabel: 'Shkendija vs Hibernian' },
  { name: 'David Gray', refId: '270vqal4mwrs6pk', matchStatus: 'finished', matchLabel: 'Shkendija vs Hibernian' },
  { name: 'Enrico Maaßen', refId: 'mfiws1aode3sdxd', matchStatus: 'finished', matchLabel: 'St. Gallen vs Sheriff Tiraspol' },
  { name: 'Victor Mihailov', refId: 'bm0nxitog6hs3t6', matchStatus: 'finished', matchLabel: 'St. Gallen vs Sheriff Tiraspol' },
];
